### ISSUE TITLE
Files with odd IFD offsets

### ISSUE THREAD

**Issue by csboling** [yigolden/TiffLibrary#5]
The TIFF spec is unambiguous that IFD offsets shall be word-aligned, and TiffLibrary currently throws `InvalidDataException` when this is not the case. In practice however, _many_ files in the wild violate this requirement, and most software can handle these files. As far as I can tell the decoder does not rely on this assumption and decodes such files fine if the checks for this ([here](https://github.com/yigolden/TiffLibrary/blob/e21b6e0babcc2196c557227b20789a1efc29ad63/src/TiffLibrary/TiffFileHeader.cs#L132) and [here](https://github.com/yigolden/TiffLibrary/blob/e21b6e0babcc2196c557227b20789a1efc29ad63/src/TiffLibrary/TiffFileHeader.cs#L176)) are removed. An option like "strict mode" for rejecting such files might allow for detecting spec violations while still being able to open files with this common spec noncompliance.

Some brief discussion [here](https://www.asmail.be/msg0054752394.html), archived from the libtiff mailing list from 2005.

**Comment by MM-YJN** [comment]
Thanks for finding this! The restriction was removed in [v0.5.263](https://www.nuget.org/packages/TiffLibrary/0.5.263).
